apiVersion: apps/v1
kind: Deployment
metadata:
  name: sobrian-web
  labels:
    app: sobrian-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sobrian-web
  template:
    metadata:
      labels:
        app: sobrian-web
    spec:
      containers:
      - name: sobrian-web
        image: sobrian/sobrian-web:0.1.0
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: sobrian-web
spec:
  selector:
    app: sobrian-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  # type: NodePort

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: sobrian-web
#   annotations:
#     kubernetes.io/ingress.class: azure/application-gateway
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           service:
#             name: sobrian-web
#             port:
#               number: 80
#         pathType: Exact